version: '3.8'

name: ensemble

x-environment: &environment
  TZ: UTC
  NODE_ENV: local
  MYSQL_HOST: mysql
  MYSQL_PORT: 3306
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: ensemble
  MYSQL_DATABASE: ensemble
  MYSQL_SYNCHRONIZE: false

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: ensemble
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/disk:/disk
    networks:
      - ensemble

  redis:
    build:
      context: ./redis
      dockerfile: dockerfile
    command: redis-server --port 6379
    ports:
      - 6380:6379
    volumes:
      - ./data:/data

  admin:
    build:
      context: .
      dockerfile: admin/dockerfile
    environment:
      <<: *environment
      JWT_ADMIN_ACCESS_SECRET: jwt-admin-atk
      JWT_ADMIN_REFRESH_SECRET: jwt-admin-rtk
    ports:
      - 4000:4000
    volumes:
      - ./admin/logs:/var/app/logs
    networks:
      - ensemble

  client:
    build:
      context: .
      dockerfile: client/dockerfile
    environment:
      <<: *environment
      JWT_CLIENT_ACCESS_SECRET: jwt-client-atk
      JWT_CLIENT_REFRESH_SECRET: jwt-client-rtk
    ports:
      - 4001:4001
    volumes:
      - ./client/logs:/var/app/logs
    networks:
      - ensemble

  stream:
    build:
      context: .
      dockerfile: stream/dockerfile
    environment:
      <<: *environment
      JWT_CLIENT_ACCESS_SECRET: jwt-client-atk
      JWT_CLIENT_REFRESH_SECRET: jwt-client-rtk
    ports:
      - 4002:4002
    volumes:
      - ./stream/logs:/var/app/logs
    networks:
      - ensemble

networks:
  ensemble:
    driver: bridge
